--- 
- hosts: all
  become: true
  
  tasks:

   - name: update 
     apt: 
       update_cache: yes

   - name: Install certif
     apt: 
       name: ca-certificates
       state: present 

   - name: Install curl
     apt: 
       name: curl
       state: present 
    
   - name: Install gnupg
     apt:
       name: gnupg           
       state: present

   - name: GPGKey
     shell: 'curl -fsSL http://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg'

   - name: echo
     shell: | 
       echo \
       "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian \
       $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

   - name: Run apt
     apt: 
       update_cache: yes

   - name: install docker
     apt:
       name: docker-ce
       state: present
    
   - name: install docker ce cli
     apt:
       name: docker-ce-cli
       state: present
 
   - name: install containerd io
     apt:
       name: containerd.io
       state: present
